### ISSUE TITLE
OCR on full pages

### ISSUE THREAD

**Issue by Aethor** [gsoykan/comics_ocr#1]
Hi,

I tried to use this repository to perform OCR on a modern comics. I performed OCR on full pages of the comics, and I did not have good results. I troubleshooted the issue and found that, if I only try to OCR a single speech bubble, the model works pretty well and the output is nearly flawless.

It seems to me that one should perform bubble detection before performing OCR on each bubble. From my experiments, one could order bubbles using Morton order, which seems to work decently well.

However, it seems this repository only performs text line detection. I did not find any model in [COMICS Text+](https://github.com/gsoykan/comics_text_plus) to perform bubble detection, even though such a model is described in the [COMICS paper](https://arxiv.org/pdf/1611.05118.pdf) at the end of Section 2.2. Is this model available anywhere?

**Comment by gsoykan** [comment]
Hi @Aethor,

Firstly, I apologize for the delayed response; wrapping up the fall term was quite challenging. 

Your observations regarding the OCR performance on individual speech bubbles versus full comic pages are indeed accurate. As you've correctly identified, performing bubble detection before OCR can significantly enhance the accuracy. This approach is not currently incorporated into the repository, and as you've noted, the specific model discussed in the COMICS paper (end of Section 2.2) is not available here.

However, there's a viable alternative. You can develop a simple bubble detection model using YOLO architectures, particularly with datasets like DCM772. In my thesis, which builds upon this work, I've addressed this issue in greater detail and have further refined the architecture initially presented in ["Comic MTL: optimized multi-task learning for comic book image analysis"](https://www.semanticscholar.org/paper/Comic-MTL%3A-optimized-multi-task-learning-for-comic-Nguyen-Rigaud/684726bf4cd22b09110ae62faa899617b8b00e2f). For more comprehensive insights, I invite you to read [my thesis](https://drive.google.com/file/d/1DGknajaUjQv_Dst99NweE_lPSLI6gmZx/view), particularly Chapter 3, where I elaborate on how I improved the model.

I hope this information assists you in your endeavors, and I appreciate your interest and usage of my work. 

Best!

**Comment by Aethor** [comment]
Thanks for your answer!
